# ---------------------------
# APP
# ---------------------------
spring.application.name=NutricionYDeporte
server.port=8080

# ---------------------------
# DATABASE (PostgreSQL)
# ---------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/PRUEBA45
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.auto-commit=false

# ---------------------------
# JPA / Hibernate
# ---------------------------
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.hbm2ddl.auto=create-drop
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.open-in-view=true

# ---------------------------
# CORS para Webflux
# ---------------------------
spring.webflux.cors.allowed-origins=*
spring.webflux.cors.allowed-methods=*
spring.webflux.cors.allowed-headers=*
spring.webflux.cors.allow-credentials=true

# ---------------------------
# JSON / Formato fechas
# ---------------------------
spring.jackson.date-format=yyyy-MM-dd

# ---------------------------
# LOGGING
# ---------------------------
logging.level.com.rnyd.rnyd.service.signInService.SignInService=INFO

# ---------------------------
# SEGURIDAD / JWT
# ---------------------------
security.secret-key=claveSuperSecreta123456